application: taipeisportstar
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/stadiums/(all|type/.*|sport/.*)
  script: stadium.app
- url: /api/sports/(all|type/.*)
  script: sport.app
- url: /api/event/create/(\d*)
  script: event.app
- url: /api/event/select/(all|id/.*)
  script: event.app

- url: /.*
  script: taipeisportstar.app

- url: /(.*\.txt)
  static_files: /\1
  upload: /(.*\.txt)